// <auto-generated />
using Hotel_WPF.DAL.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotel_WPF.DAL.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hotel_WPF.DAL.Entities.Facilities", b =>
                {
                    b.Property<int>("IdFacilities")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFacilities"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFacilities");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            IdFacilities = 1,
                            Name = "Bathroom"
                        },
                        new
                        {
                            IdFacilities = 2,
                            Name = "TV"
                        },
                        new
                        {
                            IdFacilities = 3,
                            Name = "Balcony"
                        },
                        new
                        {
                            IdFacilities = 4,
                            Name = "Kitchen"
                        },
                        new
                        {
                            IdFacilities = 5,
                            Name = "Hairdryer"
                        });
                });

            modelBuilder.Entity("Hotel_WPF.DAL.Entities.Image", b =>
                {
                    b.Property<int>("IdImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImage"), 1L, 1);

                    b.Property<int>("IdRoom")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdImage");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            IdImage = 1,
                            IdRoom = 1,
                            Name = "Camera 1",
                            Path = "E:\\Proiecte\\Hotel\\Hotel-WPF\\Hotel-WPF\\Resources\\room1.jpg"
                        });
                });

            modelBuilder.Entity("Hotel_WPF.DAL.Entities.Offer", b =>
                {
                    b.Property<int>("IdOffer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOffer"), 1L, 1);

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOffer");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            IdOffer = 1,
                            Discount = 35,
                            EndDate = "27.12",
                            Name = "Oferta Craciun",
                            StartDate = "20.12"
                        });
                });

            modelBuilder.Entity("Hotel_WPF.DAL.Entities.Price", b =>
                {
                    b.Property<int>("IdPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrice"), 1L, 1);

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdRoomType")
                        .HasColumnType("int");

                    b.Property<float>("MyPrice")
                        .HasColumnType("real");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPrice");

                    b.ToTable("Prices");

                    b.HasData(
                        new
                        {
                            IdPrice = 1,
                            EndDate = "01.06.2022",
                            IdRoomType = 1,
                            MyPrice = 550f,
                            StartDate = "01.01.2022"
                        });
                });

            modelBuilder.Entity("Hotel_WPF.DAL.Entities.Reservation", b =>
                {
                    b.Property<int>("IdReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReservation"), 1L, 1);

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdOffer")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("NrAdults")
                        .HasColumnType("int");

                    b.Property<int>("NrChildren")
                        .HasColumnType("int");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdReservation");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            IdReservation = 1,
                            EndDate = "26.12.2021",
                            IdOffer = 1,
                            IdUser = 2,
                            NrAdults = 2,
                            NrChildren = 1,
                            StartDate = "21.12.2021",
                            Status = "Achitat"
                        });
                });

            modelBuilder.Entity("Hotel_WPF.DAL.Entities.ReservationService", b =>
                {
                    b.Property<int>("IdReservationService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReservationService"), 1L, 1);

                    b.Property<int>("IdReservation")
                        .HasColumnType("int");

                    b.Property<int>("IdService")
                        .HasColumnType("int");

                    b.HasKey("IdReservationService");

                    b.ToTable("ReservationServices");

                    b.HasData(
                        new
                        {
                            IdReservationService = 1,
                            IdReservation = 1,
                            IdService = 2
                        });
                });

            modelBuilder.Entity("Hotel_WPF.DAL.Entities.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRole");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRole = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            IdRole = 2,
                            Name = "Client"
                        },
                        new
                        {
                            IdRole = 3,
                            Name = "Employee"
                        },
                        new
                        {
                            IdRole = 4,
                            Name = "Unauthorized User"
                        });
                });

            modelBuilder.Entity("Hotel_WPF.DAL.Entities.Room", b =>
                {
                    b.Property<int>("IdRoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRoom"), 1L, 1);

                    b.Property<int>("IdType")
                        .HasColumnType("int");

                    b.Property<string>("IsApartament")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRoom");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            IdRoom = 1,
                            IdType = 1,
                            IsApartament = "no"
                        });
                });

            modelBuilder.Entity("Hotel_WPF.DAL.Entities.RoomFacilities", b =>
                {
                    b.Property<int>("IdRoomFacilities")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRoomFacilities"), 1L, 1);

                    b.Property<int>("IdFacilities")
                        .HasColumnType("int");

                    b.Property<int>("IdRoom")
                        .HasColumnType("int");

                    b.HasKey("IdRoomFacilities");

                    b.ToTable("RoomFacilities");

                    b.HasData(
                        new
                        {
                            IdRoomFacilities = 2,
                            IdFacilities = 1,
                            IdRoom = 1
                        });
                });

            modelBuilder.Entity("Hotel_WPF.DAL.Entities.RoomReservation", b =>
                {
                    b.Property<int>("IdRoomReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRoomReservation"), 1L, 1);

                    b.Property<int>("IdReservation")
                        .HasColumnType("int");

                    b.Property<int>("IdRoom")
                        .HasColumnType("int");

                    b.HasKey("IdRoomReservation");

                    b.ToTable("RoomReservations");

                    b.HasData(
                        new
                        {
                            IdRoomReservation = 1,
                            IdReservation = 1,
                            IdRoom = 1
                        });
                });

            modelBuilder.Entity("Hotel_WPF.DAL.Entities.RoomType", b =>
                {
                    b.Property<int>("IdRoomType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRoomType"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRoomType");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            IdRoomType = 1,
                            Name = "1 bed"
                        },
                        new
                        {
                            IdRoomType = 2,
                            Name = "2 beds"
                        },
                        new
                        {
                            IdRoomType = 3,
                            Name = "3 beds"
                        },
                        new
                        {
                            IdRoomType = 4,
                            Name = "1 bed + 1 double bed"
                        },
                        new
                        {
                            IdRoomType = 5,
                            Name = "1 double bed"
                        });
                });

            modelBuilder.Entity("Hotel_WPF.DAL.Entities.Service", b =>
                {
                    b.Property<int>("IdService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdService"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("IdService");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            IdService = 1,
                            Name = "Breakfast",
                            Price = 25f
                        },
                        new
                        {
                            IdService = 2,
                            Name = "All inclusive",
                            Price = 50f
                        });
                });

            modelBuilder.Entity("Hotel_WPF.DAL.Entities.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"), 1L, 1);

                    b.Property<string>("DateOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            IdUser = 1,
                            DateOfBirth = "12.07.1986",
                            IdRole = 1,
                            Mail = "admin@gmail.com",
                            Name = "Administrator Sef",
                            Password = "admin1234",
                            PhoneNumber = "0755894682",
                            Surname = "Stefan"
                        },
                        new
                        {
                            IdUser = 2,
                            DateOfBirth = "15.12.1996",
                            IdRole = 2,
                            Mail = "client234@gmail.com",
                            Name = "Dan",
                            Password = "stef1234",
                            PhoneNumber = "0755890000",
                            Surname = "Stefan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
