% Represent the same on a tennis ball can be generated by the following
% parametric relations:
%   /
%  |   x = a*cos(t+pi/4)-b*cos(3*(t+pi/4))
%  |                                      ,a = 1, b = 2, c = 4ab,
%  |                                             t ∈ [0,2*pi]
%  |   y = a*sin(t+pi/4)-b*sin(3*(t+pi/4))
%  |   z = c*sin(2*t);
%   \

t = linspace(0, 2 * pi, 100);
a = 1;
b = 2;
c = 4 * a * b;

x = a * cos(t+ pi/4) - b * cos(3 * (t + pi/4));
y = a * sin(t+ pi/4) - b * sin(3 * (t + pi/4));
z = c * sin(2 * t);

for i=1:length(t)
    plot3(x, y, z, 'b');
    hold on
    plot3(x(i), y(i), z(i), 'og');
    hold off
    drawnow
end
